version: '3'

services:
  backend: # backend service  
    image: backend
    ports:
      - 8080:80
    container_name: 'backend1'  
   
  haproxy:  # Haproxy service  
    image: proxy  
    ports:  
      - 80:80
    container_name: 'haproxy'   
